### ISSUE TITLE
TestCafe fails to log in to Outlook / MS Teams - Parse Error: Header overflow

### ISSUE THREAD

**Issue by Marketionist** [DevExpress/testcafe#5083]
### What is your Test Scenario?
I need to perform some tests in Microsoft Outlook / Microsoft Teams, but after clicking on Outlook / Teams icon inside Microsoft's portal TestCafe throws an error.
 
### What is the Current behavior?
Testcafe fails to log in to Outlook / MS Teams - `Error: Parse Error: Header overflow` is thrown.
 
### What is the Expected behavior?
TestCafe logs in to Microsoft Outlook / Microsoft Teams.
 
### What is your web application and your TestCafe test code?

<summary>Your complete test code (or attach your test files):</summary>

```js
// test.js
const { Role, Selector } = require('testcafe');

fixture('My test');

const username = '***';
const password = '***';

const testrole = Role('https://login.microsoftonline.com/', async t => {
    await t
        .typeText(
            Selector('input').withAttribute('type', 'email'),
            username
        )
        .click(Selector('#idSIButton9'))
        .typeText(
            Selector('input').withAttribute('type', 'password'),
            password
        )
        .click(Selector('#idSIButton9'))
        .click(Selector('#idBtn_Back'));
}, { preserveUrl: true });

test('Login', async t => {
    await t.navigateTo('https://www.office.com');

    await t.useRole(testrole);

    await t.click(Selector('.ms-ohp-Icon--outlookLogo'));

    // Comment out the previous line ^ and uncomment the next line to log in to MS Teams
    // await t.click(Selector('.ms-ohp-Icon--teamsLogo'));

    await t.debug();
});
```

<summary>Your complete test report:</summary>

```
My test
 ✖ Login

   1) A request to "https://outlook.office.com/owa/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
      
      Error details:
      Failed to perform a request to the resource at "https://outlook.office.com/owa/" because of an error.
      Error: Parse Error: Header overflow

      Browser: Chrome 81.0.4044.138 / macOS 10.11.6

         23 |test('Login', async t => {
         24 |    await t.navigateTo('https://www.office.com');
         25 |
         26 |    await t.useRole(testrole);
         27 |
       > 28 |    await t.click(Selector('.ms-ohp-Icon--outlookLogo'));
         29 |
         30 |    await t.debug();
         31 |});
         32 |
```

### Steps to Reproduce:

1. Create `test.js` with the code provided above
2. Execute it: `testcafe chrome test.js --disable-page-caching --skip-js-errors`
3. See the error: `Error: Parse Error: Header overflow`
 
### Your Environment details:
 
* testcafe version: 1.8.4, 1.8.5-alpha.3
* node.js version: 12.13.1, 10.15.1
* command-line arguments: testcafe chrome test.js --disable-page-caching --skip-js-errors
* browser name and version: Chrome 81.0.4044.138
* platform and version: macOS 10.15, macOS 10.11

**Comment by AlexanderMoiseev** [comment]
Hello, I’ve tried to reproduce the issue and your test does not seem to work for me because there is no ‘#idBtn_Back' selector on the page.
![loginToOffice](https://user-images.githubusercontent.com/1498953/82322466-3b4ed400-99df-11ea-9d54-2218d8e99721.png)

However, If I comment out the following line, then the test is passed. 

` await t.click(Selector('#idBtn_Back'));`

Would you please clarify what you tried to accomplish using this code line? I suggest you try to navigate to the required page directly. This should solve the issue.
If the problem persists, please provide a video illustrating steps to reproduce it.

**Comment by Marketionist** [comment]
Hello @AlexanderMoiseev sure, I'll be happy to provide more info:

1.  `'#idBtn_Back'` is a "No" button for "Do this to reduce the number of times you are asked to sign in." page (it appears after the password was provided and the "Sign in" button was clicked - see the screenshot and the screencast).
![testcafe-outlook-teams-bug-btn-no](https://user-images.githubusercontent.com/534603/82363139-6d5e3700-99db-11ea-8007-138cb67911cb.png)

2. Please see the video screencast illustrating steps to reproduce (`testcafe-outlook-teams-bug2.mp4`): https://www.sendspace.com/file/xkq5uy

I really hope this will help, as for now there is no way to log in to Microsoft Outlook or Microsoft Teams with TestCafe (even through direct links) without being blocked by `Error: Parse Error: Header overflow` error.

Also, please let me know if any additional information will be needed - I'll be happy to help!

**Comment by SergeyShurygin** [comment]
Hi @Marketionist ,

TestCafe uses Node.js, which limits the maximum HTTP header size. The default limit value for the 10.15 and the 12.13 Node.js versions is 8KB, which is not enough for outlook.office.com. You can use the Node.js [–max-http-header-size](https://nodejs.org/api/cli.html#cli_max_http_header_size_size) option to increase it.

**Comment by Marketionist** [comment]
Hello @SergeyShurygin,

Running TestCafe tests with
```
node --max-http-header-size=9999999 ./node_modules/.bin/testcafe chrome test.js --disable-page-caching --skip-js-errors
```
does not fix the problem - still getting `Error: Parse Error: Header overflow`

Tested on Node.js versions: 10.15.1, 12.13.1, 14.3.0 - the problem is still actual.

**Comment by SergeyShurygin** [comment]
Hi,
 
./node_modules/.bin/testcafe is an intermediate script that filters node.js arguments and runs node_modules/testcafe/bin/testcafe.js on a new node process. To pass the --max-http-header-size option to it, you need to use the NODE_OPTIONS environment variable or run node_modules/testcafe/bin/testcafe.js directly, e.g.
`node --max-http-header-size=1024000 ./node_modules/testcafe/bin/testcafe.js chrome tests\test5.ts`
 
We've registered an issue ([https://github.com/inikulin/bin-v8-flags-filter/issues/9](https://github.com/inikulin/bin-v8-flags-filter/issues/9)) to allow passing the --max-http-header-size option directly.

**Comment by Marketionist** [comment]
Confirmed - working ok with updated path to testcafe:
```
node --max-http-header-size=1024000 ./node_modules/testcafe/bin/testcafe.js chrome test.js --disable-page-caching --skip-js-errors
```

Thank you a lot @SergeyShurygin!
