### ISSUE TITLE
Testcafe and new version of QlikSense

### ISSUE THREAD

**Issue by JasminKostic** [DevExpress/testcafe#7320]
### What is your Scenario?

As a tester i would like to perform automated checks and procedures as user for E2E tests.
I would like to open my site -> open QlikSense app -> navigate to QlikSense HUB -> Open QlikSense application -> Open sheet from application -> continue with various tests on site

### What is the Current behavior?

After upgrading QlikSense to latest August2022 version for all tests following errors appear:
Currently on step to "Open QlikSense application" 2 errors are thrown
![errors](https://user-images.githubusercontent.com/115016359/193836541-e950fe0e-ef7a-4d34-9e1e-66285749cf32.png)

### What is the Expected behavior?

When opening an application from QlikSense HUB, that application should open like in previous versions

### What is your public website URL? (or attach your complete example)

https://demos.qlik.com/qliksense

### What is your TestCafe test code?

[DemoForGithub.zip](https://github.com/DevExpress/testcafe/files/9707543/DemoForGithub.zip)

1. unzip solution
2. use "npm install" to install modules
3. execute tests by command line "testcafe" or "testcafe firefox DemoTest.ts"

### Your complete configuration file

{
    "browsers": [
      "chrome",
      "firefox",
      "edge"
    ],
    "src": [
      "*.ts"
    ],
    "reporter": [
      {
        "name": "spec"
      },
      {
        "name": "xunit",
        "output": "reports/report.xml"
      }
    ],
    "screenshots": {
      "screenshotPath": "reports/screenshots/",
      "takeOnFails": true,
      "screenshotPathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    }
  }

### Steps to Reproduce

1.Open main page
2.Open QlikSense HUB
3.Open QlikSense application
error thrown, app not opened

### TestCafe version

1.18.5

### Node.js version

12.16.3

### Command-line arguments

testcafe firefox DemoTest.ts

### Platform(s) and version(s)

Windows

**Comment by AlexKamaev** [comment]
Thank you for the example. I managed to reproduce the issue. We need additional time to research it.

To the team:
I reproduced it with the latest `testcafe-hammerhead` version in the http-playground.

**Comment by hasan-assi** [comment]
Thanks @AlexKamaev for reproducing and confirming the bug! This bug is a major blocker for our releases right now. 
Do you know by any somehow when this bug may get fixed? And if there is any guidence of how we can speed up the fix, it would be highly appreicated.

**Comment by AlexKamaev** [comment]
We have not yet started investigating this issue. Any personal estimates may be misleading, so at this moment, I cannot give you any specific time frames on when the issue will be fixed.

**Comment by hasan-assi** [comment]
> We have not yet started investigating this issue. Any personal estimates may be misleading, so at this moment, I cannot give you any specific time frames on when the issue will be fixed.

Thanks @AlexKamaev for your reponse!

**Comment by miherlosev** [comment]
Hi @JasminKostic,

TestCafe runs tests using the [URL-rewritten](https://github.com/devexpress/testcafe-hammerhead) proxy.
This approach is good. However, there is a way to improve the stability and speed of test execution - the native browser automation API.
We have a test execution mode uses native browser automation - we call it the `Proxyless` mode.
In `Proxyless` mode, a few issues are already fixed.
By the way, this issue was also fixed in `Proxyless` mode.
Try running your tests in `Proxyless` mode and let us know the results.
This option is available in all interfaces:

```js
// Command-line
testcafe chrome tests --experimental-proxyless

// Programmatic
testcafe
    .createRunner
	.src('tests')
	.browsers('chrome')
	.run({ experimentalProxyless: true });
	
// Configuration file
{
   "experimentalProxyless": "true"
}	
```

Note that at present it is an experimental mode.
Also, the `Proxyless` mode is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.

**Comment by Jazz91** [comment]
Hi @miherlosev Thank you for your reply, 

The proxyless mode didn't solve the issue as testcafe was not the root-cause.
We upgraded our QlikSense server application to latest November2022 and with the new release it was fixed from their side.
With that I'm happy to say that the issue is resolved.

Thanks and best regards

**Comment by JasminKostic** [comment]
Hi @miherlosev Thank you for your reply,

The proxyless mode didn't solve the issue as testcafe was not the root-cause.
We upgraded our QlikSense server application to latest November2022 and with the new release it was fixed from their side.
With that I'm happy to say that the issue is resolved.

Thanks and best regards

**Comment by miherlosev** [comment]
I'm happy to hear that everything works for you now. Should the issue return, feel free to drop us a line.
